# Generated by Django 2.2.6 on 2020-05-31 19:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200506_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 19, 30, 9, 201129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 19, 30, 9, 200131, tzinfo=utc)),
        ),
    ]
