# Generated by Django 2.2.6 on 2019-12-13 16:43
# Generated by Django 2.2.6 on 2019-12-13 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='ID',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 16, 42, 43, 828727, tzinfo=utc)),
        ),
    ]
