# Generated by Django 2.2.6 on 2019-12-13 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191214_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 16, 51, 23, 187462, tzinfo=utc)),
        ),
    ]
