# Generated by Django 2.2.6 on 2020-01-26 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191214_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 10, 23, 2, 921162, tzinfo=utc)),
        ),
    ]
