# Generated by Django 2.2.6 on 2020-01-26 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200126_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 10, 38, 32, 21488, tzinfo=utc)),
        ),
    ]
