# Generated by Django 2.2.6 on 2020-01-28 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200128_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 2, 14, 23, 990747, tzinfo=utc)),
        ),
    ]
